# Generated by Django 5.2.1 on 2025-05-30 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_exchangeoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoffer',
            name='user_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_exchange_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='user_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchange_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
